public class CarLeasingWrapper {
    @AuraEnabled
    public String discountType{get;set;}
    @AuraEnabled
    public Double discountValue{get;set;}
    @AuraEnabled
    public String discountName{get;set;}
    @AuraEnabled
    public String pictureUrl{get;set;}
    @AuraEnabled
    public String manufacturer{get;set;}
    @AuraEnabled
    public String model{get;set;}
    @AuraEnabled
    public Integer horsepower{get;set;}
    @AuraEnabled
    public Date productionYear{get;set;}
    @AuraEnabled
    public String review{get;set;}
    @AuraEnabled
    public Double price{get;set;}
    @AuraEnabled
    public String bodyType{get;set;}
    @AuraEnabled
    public String gearbox{get;set;}
    @AuraEnabled
    public String engineType{get;set;}
    @AuraEnabled
    public Integer numberOfSeats{get;set;}
    @AuraEnabled
    public Double acceleration{get;set;}
    @AuraEnabled
    public Double averageFuelConsumption{get;set;}
    @AuraEnabled
    public Double engineCapacity{get;set;}
    @AuraEnabled
    public Integer carHeight{get;set;}
    @AuraEnabled
    public Integer carWidth{get;set;}
    @AuraEnabled
    public Integer carLength{get;set;}
    @AuraEnabled
    public Integer theSizeOfTheWheels{get;set;}
}